new_local_repository(
    name = "htslib",
    build_file = "BUILD.bazel",
    path = "/htslib",
)

new_local_repository(
    name = "bcftools",
    build_file = "BUILD.bazel",
    path = "/bcftools",
)

#run cat ref.fastq | ./TestRead  calls.vcf.gz
